function predCount = hawkes_predict_count_interval(historyTimes,predStart,predEnd,mu,alpha,beta)

% Predicts the expected number of Hawkes events over a future interval.
% The Hawkes intensity is lambda(t) = mu + sum_{k=1}^K alpha_k g_k(t),
% where g_k(t) = sum_{t_i < t} exp(-beta_k*(t-t_i)).
% The function conditions on the observed event history before predStart
% and computes the expected number of events over [predStart, predEnd]
%
% INPUTS:
%   historyTimes : vector of observed event times available before the
%                  prediction origin. Only events satisfying historyTimes < predStart
%                  are used to initialize the Hawkes state.
%   predStart    : prediction origin.
%   predEnd      : end of the prediction interval. It must satisfy predEnd > predStart
%   mu           : nonnegative baseline intensity.
%   alpha        : K x 1 vector of nonnegative excitation coefficients
%                  alpha_k.
%   beta         : K x 1 vector of strictly positive exponential
%                  decay parameters beta_k.
%
% OUTPUT:
%   predCount    : scalar predicted expected number of events over
%                  [predStart,predEnd].
%                  The prediction conditions on the observed Hawkes
%                  state at predStart and accounts for both:
%                    1. excitation generated by past observed events;
%                    2. excitation generated recursively by future
%                       events occurring inside the forecast interval.
%                  If the supplied Hawkes parameters are invalid or
%                  the resulting prediction is nonfinite or negative,
%                  predCount is returned as NaN.

historyTimes = historyTimes(:);
alpha = alpha(:);
beta  = beta(:);

if mu < 0 || any(alpha < 0) || any(beta <= 0) || any(~isfinite([mu; alpha; beta]))
    predCount = NaN;
    return;
end

K = numel(beta);

if predEnd <= predStart
    error('predEnd must be larger than predStart.');
end

H = predEnd - predStart;

g0 = zeros(K,1);
hist = historyTimes(historyTimes < predStart);

for k = 1:K
    if isempty(hist)
        g0(k) = 0;
    else
        g0(k) = sum(exp(-beta(k) * (predStart - hist)));
    end
end

Amean = ones(K,1) * alpha.' - diag(beta);

M = zeros(K+2, K+2);
M(1:K, 1:K) = Amean;
M(1:K, end) = mu * ones(K,1);
M(K+1, 1:K) = alpha.';
M(K+1, end) = mu;

z0 = [g0; 0; 1];
zH = expm(M * H) * z0;

predCount = zH(K+1);

if ~isfinite(predCount) || predCount < 0
    predCount = NaN;
end