function predCount = hawkes_predict_count_interval(historyTimes,predStart,predEnd,mu,alpha,beta)

% Computes the conditional expected number of Hawkes events over a
% future prediction interval.
%
% INPUTS:
%   historyTimes : vector of observed event times. Only events satisfying historyTimes < predStart
%                  are used to initialize the Hawkes state at the prediction origin
%   predStart    : starting time of the prediction interval
%   predEnd      : ending time of the prediction interval. It must satisfy predEnd > predStart
%   mu           : nonnegative baseline intensity
%   alpha        : K x 1 vector of nonnegative excitation parameters alpha_k
%   beta         : K x 1 vector of strictly positive decay parameters beta_k
%
% OUTPUT:
%   predCount    : scalar conditional expected number of events over
%                      [predStart,predEnd].
%                  Here predCount = E[N(predEnd)-N(predStart) | F_predStart],
%                  where F_predStart denotes the observed event history
%                  available at predStart
%                  The forecast accounts for both the excitation from
%                  events observed before predStart and the additional
%                  excitation generated by future events occurring
%                  within the prediction interval.
%                  If the supplied parameters are invalid or the computed
%                  forecast is nonfinite or negative, predCount is NaN.

historyTimes = historyTimes(:);
alpha = alpha(:);
beta  = beta(:);

if mu < 0 || any(alpha < 0) || any(beta <= 0) || any(~isfinite([mu; alpha; beta]))
    predCount = NaN;
    return;
end

K = numel(beta);

if predEnd <= predStart
    error('predEnd must be larger than predStart.');
end

H = predEnd - predStart;

g0 = zeros(K,1);
hist = historyTimes(historyTimes < predStart);

for k = 1:K
    if isempty(hist)
        g0(k) = 0;
    else
        g0(k) = sum(exp(-beta(k) * (predStart - hist)));
    end
end

Amean = ones(K,1) * alpha.' - diag(beta);

M = zeros(K+2, K+2);
M(1:K, 1:K) = Amean;
M(1:K, end) = mu * ones(K,1);
M(K+1, 1:K) = alpha.';
M(K+1, end) = mu;

z0 = [g0; 0; 1];
zH = expm(M * H) * z0;

predCount = zH(K+1);

if ~isfinite(predCount) || predCount < 0
    predCount = NaN;
end